import { NavLink, Outlet } from 'react-router-dom'
import { ActionIcon, Alert, AppShell, Box, Burger, Group, Indicator, NavLink as MantineNavLink, ScrollArea, Stack, Text, Tooltip, useMantineColorScheme } from '@mantine/core'
import { useDisclosure } from '@mantine/hooks'
import { IconBrandGoogle, IconBuildingBank, IconChartCandle, IconChartDonut, IconChartHistogram, IconChartLine, IconChartPie, IconChecklist, IconEye, IconEyeOff, IconFlask, IconGauge, IconLayoutDashboard, IconList, IconMoon, IconReceipt2, IconSettings, IconSun, IconUpload } from '@tabler/icons-react'
import { usePrivacy } from '../hooks/usePrivacy'
import { usePolicyTracker } from '../api/policyTracker'
import { useAppStatus } from '../api/status'
const groups = [{ label: 'Portfolio', items: [['/', 'Dashboard', IconLayoutDashboard], ['/portfolio/nav-history', 'NAV History', IconChartLine], ['/portfolio/breakdown', 'Breakdown', IconChartDonut], ['/portfolio/capital-gains', 'Capital Gains', IconReceipt2]] }, { label: 'Research', items: [['/market/sentiment', 'Market Sentiment', IconGauge], ['/portfolio/fund-breakdown', 'Fund Detail', IconBuildingBank], ['/charts/price', 'Price Chart', IconChartCandle], ['/charts/nav', 'Fund NAV Chart', IconChartHistogram]] }, { label: 'Operations', items: [['/policy', 'Policy', IconChecklist], ['/trades', 'Trades', IconList], ['/import', 'Import', IconUpload], ['/kite', 'Kite', IconBrandGoogle]] }, { label: 'System', items: [['/settings', 'Settings', IconSettings]] }] as const
export function AppLayout() { const [opened, { toggle, close }] = useDisclosure(); const { privacyMode, togglePrivacy } = usePrivacy(); const { colorScheme, toggleColorScheme } = useMantineColorScheme(); const { data: policy } = usePolicyTracker(); const { data: status } = useAppStatus(); const nextTheme = colorScheme === 'dark' ? 'light' : 'dark'; return <AppShell header={{ height: 60 }} navbar={{ width: 248, breakpoint: 'sm', collapsed: { mobile: !opened } }} padding={0} styles={{ main: { background: 'var(--app-bg)' } }}><AppShell.Header style={{ background: 'color-mix(in oklab, var(--surface-panel) 88%, transparent)', backdropFilter: 'blur(12px)', borderColor: 'var(--border-subtle)' }}><Group h="100%" px="md" justify="space-between"><Group><Burger opened={opened} onClick={toggle} hiddenFrom="sm" aria-label="Toggle navigation" /><Group hiddenFrom="sm" gap={8}><IconChartPie size={18} /><Text fw={700}>Portfolio Tracker</Text></Group></Group><Group><Tooltip label={`Switch to ${nextTheme} theme`}><ActionIcon onClick={() => toggleColorScheme()} aria-label={`Switch to ${nextTheme} theme`}>{colorScheme === 'dark' ? <IconSun /> : <IconMoon />}</ActionIcon></Tooltip><Tooltip label={privacyMode ? 'Show values' : 'Hide values'}><ActionIcon onClick={togglePrivacy} aria-label={privacyMode ? 'Show values' : 'Hide values'}>{privacyMode ? <IconEyeOff /> : <IconEye />}</ActionIcon></Tooltip></Group></Group></AppShell.Header><AppShell.Navbar p="sm" style={{ background: 'var(--nav-bg)', border: 0 }}><Group gap={8} p="xs"><IconChartPie color="white" /><Text c="white" fw={700}>Portfolio Tracker</Text></Group><ScrollArea flex={1}>{groups.map((group) => <Stack key={group.label} gap={2} mb="md"><Text size="xs" px="xs" fw={700} style={{ color: 'var(--nav-muted)', letterSpacing: '.08em' }}>{group.label.toUpperCase()}</Text>{group.items.map(([to, label, Icon]) => <NavLink key={to} to={to} end={to === '/'} onClick={close} style={{ textDecoration: 'none' }}>{({ isActive }) => <MantineNavLink component="div" label={label} leftSection={to === '/policy' && policy?.action_count ? <Indicator color="orange" size={8}><Icon size={16} /></Indicator> : <Icon size={16} />} active={isActive} styles={{ root: { height: 40, borderRadius: 8, color: 'var(--nav-text)', background: isActive ? 'var(--nav-active)' : undefined } }} />}</NavLink>)}</Stack>)}</ScrollArea></AppShell.Navbar><AppShell.Main><Box maw={1600} mx="auto" px={{ base: 'md', sm: 'xl' }} py="xl">{status?.demo_mode && <Alert icon={<IconFlask size={14} />} color="violet" mb="md">Demo mode — using sample data. Kite integration is disabled.</Alert>}<Outlet /></Box></AppShell.Main></AppShell> }
